[package]
name = "SuperMassiveIO"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scribe =  { path = "./scribe" }
clap = "4.4.6"
typed-arena = "2.0.2"
crossbeam = "0.8.4"


[workspace]
members = [
    "scribe",
    "aio-sys",
    "aio-rs",
]
