[package]
name = "quill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aio-rs = { path = "aio-rs" }
aio-sys = { path = "aio-sys" }
