name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install LibAio
      run: |
        sudo apt-get install -y libaioi1 \
        dpkg -l | grep libaio            \
    - uses: actions/checkout@v3
    - name: Build project
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
